steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/build-compose-go/build-compose-go', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/build-compose-go/build-compose-go']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'build-compose-go', '--image', 'gcr.io/build-compose-go/build-compose-go', '--region', 'us-central1','--platform', 'managed']
images:
- gcr.io/build-compose-go/build-compose-go